import assert from "node:assert/strict";
import test from "node:test";
import {
  ApiResponseError,
  extractBackendError,
  readApiJson,
  readRetryDelay,
} from "../frontend/src/lib/api-response.ts";

const cloudFrontHtml = '<!DOCTYPE HTML><HTML><TITLE>ERROR</TITLE><BODY>403 ERROR: Request blocked. Generated by cloudfront</BODY></HTML>';

test("CloudFront HTML is never rendered as a meeting error", async () => {
  await assert.rejects(
    readApiJson(new Response(cloudFrontHtml, { status: 403, headers: { "content-type": "text/html" } })),
    (error) => {
      assert.ok(error instanceof ApiResponseError);
      assert.equal(error.status, 403);
      assert.match(error.message, /site blocked this request/i);
      assert.doesNotMatch(error.message, /HTML|DOCTYPE|cloudfront/i);
      assert.equal(error.edgeBlocked, true);
      assert.equal(readRetryDelay(error, 1), 60_000);
      assert.equal(readRetryDelay(error, 4), undefined);
      return true;
    }
  );
});

test("safe application validation messages are preserved, unknown bodies are not", () => {
  assert.equal(extractBackendError('{"error":"Refinement feedback is required."}', 400), "Refinement feedback is required.");
  assert.equal(extractBackendError('{"message":"Select an approved brief first."}', 409), "Select an approved brief first.");
  for (const body of [cloudFrontHtml, JSON.stringify({ message: cloudFrontHtml }),
    JSON.stringify({ error: { secret: "internal detail" } }), "", "internal stack trace",
    '{"error":"X-Amz-Signature=private-value"}', '{"error":"Bearer private-value"}']) {
    assert.equal(extractBackendError(body, 502), "The service is temporarily unavailable. Please try again shortly.");
  }
});

test("rate limiting retains HTTP status and respects Retry-After", async () => {
  await assert.rejects(
    readApiJson(new Response('{"error":"Please wait.","retryAfterSeconds":1}', {
      status: 429, headers: { "retry-after": "30" },
    })),
    (error) => {
      assert.equal(error.status, 429);
      assert.equal(error.retryAfterMs, 30_000);
      assert.equal(readRetryDelay(error, 5), 30_000);
      return true;
    }
  );
});

test("Retry-After accepts dates and safely bounds invalid or excessive values", async () => {
  for (const [header, body, minimum, maximum] of [
    [new Date(Date.now() + 45_000).toUTCString(), "{}", 43_000, 45_000],
    ["99999999999999", "{}", 300_000, 300_000],
    ["invalid", '{"retryAfterSeconds":7}', 7000, 7000],
    ["-1", '{"retryAfterSeconds":-1}', 30_000, 30_000],
  ]) {
    await assert.rejects(readApiJson(new Response(body, { status: 429, headers: { "retry-after": header } })),
      (error) => {
        const delay = readRetryDelay(error, 1);
        assert.ok(delay >= minimum && delay <= maximum, `${header}: ${delay}`);
        return true;
      });
  }
});

test("unauthorized, forbidden, and validation errors are not retried", () => {
  for (const status of [400, 401, 403, 404, 409, 422]) {
    assert.equal(readRetryDelay(new ApiResponseError("Request rejected", status), 1), undefined);
  }
  assert.equal(readRetryDelay(new Error("Invalid client scope"), 1), undefined);
});

test("application 403 responses cannot be confused with a temporary CloudFront page", async () => {
  await assert.rejects(readApiJson(new Response('{"error":"Client access denied"}', { status: 403 })),
    (error) => {
      assert.equal(error.edgeBlocked, false);
      assert.equal(readRetryDelay(error, 1), undefined);
      return true;
    });
});

test("network and temporary server failures have bounded retries", () => {
  for (const error of [new TypeError("Failed to fetch"), new ApiResponseError("Unavailable", 503)]) {
    assert.deepEqual([1, 2, 3, 4].map((count) => readRetryDelay(error, count)), [1500, 3000, 6000, undefined]);
  }
});

test("accepted and complete JSON responses retain the existing contract", async () => {
  for (const status of [200, 202]) {
    const body = { jobId: "test-job", status: status === 202 ? "queued" : "complete" };
    assert.deepEqual(await readApiJson(new Response(JSON.stringify(body), { status })), body);
  }
  await assert.rejects(readApiJson(new Response(cloudFrontHtml, { status: 200 })), /unexpected response/);
});
