function Get-PilarPrepStorageName {
  param(
    [Parameter(Mandatory = $true)][string]$Purpose,
    [Parameter(Mandatory = $true)][string]$AccountId,
    [Parameter(Mandatory = $true)][string]$Region,
    [string]$EnvironmentName = "demo"
  )
  $name = "pilarprep-$EnvironmentName-$Purpose-$AccountId-$Region".ToLowerInvariant()
  if ($AccountId -notmatch '^[0-9]{12}$' -or $name -notmatch '^[a-z0-9][a-z0-9-]{1,61}[a-z0-9]$') {
    throw "The requested storage name is not a valid S3 bucket name."
  }
  return $name
}

function Resolve-PilarPrepBucketParameter {
  param(
    [Parameter(Mandatory = $true)][string]$StackName,
    [Parameter(Mandatory = $true)][string]$ParameterName,
    [Parameter(Mandatory = $true)][string]$DefaultName,
    [Parameter(Mandatory = $true)][string]$Region,
    [string]$Profile = ""
  )
  $arguments = @("cloudformation", "describe-stacks", "--stack-name", $StackName,
    "--region", $Region, "--query", "Stacks[0].Parameters", "--output", "json")
  if ($Profile) { $arguments += @("--profile", $Profile) }
  $output = & aws @arguments 2>&1
  if ($LASTEXITCODE -ne 0) {
    if (($output -join " ") -match 'Stack with id .+ does not exist') { return $DefaultName }
    throw "Could not read existing storage settings for $StackName. Refresh credentials before deploying."
  }
  $parameters = ($output -join "`n") | ConvertFrom-Json
  $match = $parameters | Where-Object { $_.ParameterKey -eq $ParameterName } | Select-Object -First 1
  # An absent/empty name on an existing stack means CloudFormation still owns an autogenerated bucket.
  # Preserve that setting until an explicit data migration has completed.
  if ($null -eq $match) { return "" }
  return [string]$match.ParameterValue
}

function Resolve-PilarPrepKnowledgeBaseGeneration {
  param(
    [string]$StackName,
    [string]$Region,
    [string]$Profile,
    [string]$DefaultGeneration = "v2"
  )
  $value = Resolve-PilarPrepBucketParameter -StackName $StackName -ParameterName "KnowledgeBaseGeneration" -DefaultName $DefaultGeneration -Region $Region -Profile $Profile
  if ($value) { return $value }
  return $DefaultGeneration
}
