export class ApiResponseError extends Error {
  status: number;
  retryAfterMs?: number;
  edgeBlocked: boolean;

  constructor(message: string, status: number, retryAfterMs?: number, edgeBlocked = false) {
    super(message);
    this.name = "ApiResponseError";
    this.status = status;
    this.retryAfterMs = retryAfterMs;
    this.edgeBlocked = edgeBlocked;
  }
}

function responseRecord(body: string): Record<string, unknown> | undefined {
  try {
    const parsed: unknown = JSON.parse(body);
    if (parsed && typeof parsed === "object" && !Array.isArray(parsed)) {
      return parsed as Record<string, unknown>;
    }
  } catch {
    // Edge errors may be HTML rather than the application's JSON contract.
  }
  return undefined;
}

export function extractBackendError(body: string, status = 0) {
  const parsed = responseRecord(body);
  const message = parsed?.error ?? parsed?.message;
  if (
    typeof message === "string" && message.trim() && message.length <= 500 &&
    !/<[^>]*>|X-Amz-|Bearer\s/i.test(message)
  ) {
    return message.trim();
  }
  if (status === 429) {
    return "The site is receiving too many requests. Please wait briefly before trying again.";
  }
  if (status === 401) {
    return "Your session has expired. Sign in again to continue.";
  }
  if (status === 403) {
    return "The site blocked this request. Try again shortly. Your saved work is unchanged.";
  }
  if (status === 404) {
    return "This item is no longer available in the selected workspace.";
  }
  if (status >= 500) {
    return "The service is temporarily unavailable. Please try again shortly.";
  }
  return "The request could not be completed. Please try again.";
}

function retryAfterMilliseconds(response: Response, body: string) {
  const header = response.headers.get("retry-after")?.trim();
  let delay: number | undefined;
  if (header) {
    delay = /^\d+(\.\d+)?$/.test(header)
      ? Number(header) * 1000
      : Date.parse(header) - Date.now();
  }
  if (delay === undefined || !Number.isFinite(delay) || delay < 0) {
    const seconds = responseRecord(body)?.retryAfterSeconds;
    delay = typeof seconds === "number" ? seconds * 1000 : undefined;
  }
  return delay !== undefined && Number.isFinite(delay) && delay >= 0
    ? Math.min(delay, 300_000)
    : undefined;
}

export async function readApiJson(response: Response): Promise<unknown> {
  const body = await response.text();
  if (!response.ok) {
    throw new ApiResponseError(
      extractBackendError(body, response.status),
      response.status,
      retryAfterMilliseconds(response, body),
      response.status === 403 && /<html|<!doctype html/i.test(body) &&
        /generated by cloudfront/i.test(body) && /request blocked/i.test(body)
    );
  }
  try {
    return JSON.parse(body) as unknown;
  } catch {
    throw new ApiResponseError(
      "The service returned an unexpected response. Please try again.",
      response.status
    );
  }
}

// Only retry reads. A delayed status response must never submit another AI job.
export function readRetryDelay(error: unknown, consecutiveFailures: number) {
  if (error instanceof ApiResponseError && error.status === 429) {
    return Math.max(750, error.retryAfterMs ?? 30_000);
  }
  if (error instanceof ApiResponseError && error.edgeBlocked) {
    return consecutiveFailures <= 3 ? 60_000 : undefined;
  }
  const transient = error instanceof TypeError || (
    error instanceof ApiResponseError && [500, 502, 503, 504].includes(error.status)
  );
  if (!transient || consecutiveFailures > 3) return undefined;
  return Math.max(750, error instanceof ApiResponseError && error.retryAfterMs !== undefined
    ? error.retryAfterMs
    : Math.min(15_000, 1500 * 2 ** (consecutiveFailures - 1)));
}
